# Use postgres/example user/password credentials
version: '3.3'

services:

  db:
    image: postgres
    restart: always
    networks:
      - default
    volumes:
      - postgres_db:/var/lib/postgresql/data
    expose:
      - 5432 # Publishes 5433 to other containers but NOT to host machine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=example

  adminer:
    image: adminer
    restart: always
    networks:
      - default
    ports:
      - 8080:8080

volumes:
  postgres_db:

networks:
  default:
    name: postgres-net
